---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eksdemo-deployment
  namespace: default
  labels:
    app: eksdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksdemo
  template:
    metadata:
      labels:
        app: eksdemo 
    spec:
      containers:
      - name: eksdemo
        image: public.ecr.aws/f4k7f0q5/nsecr:latest
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1beta1
kind: Service
metadata:
  name: eksdemo-service
spec:
  selector:
    app: eksdemo 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
